### ISSUE TITLE
[e10s] Multiprocess compatibility

### ISSUE THREAD

**Issue by Turkal** [ivovk/Axon#10]
Hi,

First of all, thanks for this addon which is really useful. 

Concerning the multiprocess (e10s) compatibility, it seems like Axon isn't compatible at the moment. Do you plan to work on it should I consider that you have stopped the development ?

Best,

Marius

**Comment by ivovk** [comment]
Hi,

You're welcome. The latest version uses Google Maps, which can't be used together with Firefox addons because the Google Maps code is fetched directly from Google, and remote scripts are considered serious security vulnerabilities. I might start development again, but when Open Street Map will be implemented to conform with Firefox's security policy, I can't say. Google Maps was chosen for its educational value and ease of use.

Best,

Ivo
