### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Dostoi** [ivovk/Axon#9]
Why is the version available on the firefox addons market (I don't know the right name) 1.01 and not 2.6.8 ?

Why closing the issue if they're not solved ? (If it's because you want to stop developing the app, I can totally understand but letting them open would have avoid letting people think that they're fixed)

Why not letting the github link in the addon description to let people know that it's a foos and that they can fork it if they want to keep the app under development or push pull request ?

And at last, just want to thank you for the addon, I use it  all the time and it's really great !

**Comment by ivovk** [comment]
Hi Dostoi, 

You're welcome! Glad you like it.


The version with Google Maps 2.6.8 is not allowed on the Firefox addon website:


1) resources/axon/data/gmap.js#L63
We don't allow add-ons to use remote scripts because they create serious security vulnerabilities. We also need to review all of your add-on code, and this makes it much more difficult. Please insert those scripts locally from your add-on code.


So that's why Firefox won't update to a new version.


Ivo
---- On Mon, 16 Nov 2015 21:27:26 +0100 Dostoi &lt;notifications@github.com&gt; wrote ---- 

Why is the version available on the firefox addons market (I don't know the right name) 1.01 and not 2.6.8 ?
 Why closing the issue if they're not solved ? (If it's because you want to stop developing the app, I can totally understand but letting them open would have avoid letting people think that they're fixed)
 Why not letting the github link in the addon description to let people know that it's a foos and that they can fork it if they want to keep the app under development or push pull request ?
 And at last, just want to thank you for the addon, I use it all the time and it's really great !
